#include "aeternitas_item_catalog.h"

#include <ctype.h>
#include <string.h>

/* Room blurbs and many item slugs track AeternitasWebEdition/index.html (this.world,
 * this.items). Equipment ids 1–10 were prototype rows: descriptions here match that
 * edition's tone (sensory, dry wit) for examine/catalog depth in the 64-bit port. */

/* clang-format off — compact item catalog (slug, display label, equip hints). */
static const AetItemCatalogEntry CATALOG[] = {
    {1,  "leather_cowl",       "Leather Cowl",
     "Soft hood cut for weather, not fashion; the eye-slits trade vanity for staying dry.",
     2, 0, 1, 0},
    {2,  "rusted_iron_mail",   "Rusted Iron Mail",
     "Rings gone orange at the collar where sweat and rain kept negotiating.",
     6, 0, 8, 1},
    {3,  "woven_grass_shirt",  "Woven Grass Shirt",
     "River-reed and grass fiber plaited into a shirt that breathes louder than linen.",
     1, 0, 1, 1},
    {4,  "steel_shortsword",   "Steel Shortsword",
     "A plain blade for plain work — balance favors the wrist, not the pedigree.",
     0, 6, 3, 5},
    {5,  "wooden_buckler",     "Wooden Buckler",
     "Iron-banded oak light enough to forget until something hits the boss.",
     3, 0, 2, 6},
    {6,  "bone_ring",          "Bone Ring",
     "Carved from something that volunteered its curve; clicks once when your fist tightens.",
     1, 1, 0, 7},
    {7,  "heavy_scrap_axe",    "Heavy Scrap Axe",
     "Head welded from salvage and stubbornness; the haft hums before your shoulders complain.",
     0, 8, 6, 5},
    {8,  "leather_boots",      "Leather Boots",
     "Creased from roads that outlast the map; soles thin where optimism rubbed through.",
     2, 0, 1, 4},
    {9,  "torn_trousers",      "Torn Trousers",
     "Knees worn honest through habit; foreign stitches, familiar miles.",
     1, 0, 1, 3},
    {10, "terrible_long_item_name", "A Terribly Long Item Name That Breaks GUIs",
     "QA harness for narrow terminals: if you can read this in one line, the UI survived.",
     0, 0, 1, 7},
    {11, "abandoned_furniture", "Abandoned Furniture",
     "Splintered chairs and warped boards sag together like the last memory of a room.",
     0, 0, 9, 7},
    {12, "water_wheel",        "Water Wheel",
     "The wheel is still enough to hear the mill around it: swollen wood, old iron, and patient water.",
     0, 0, 18, 7},
    {13, "rusty_gears",        "Rusty Gears",
     "Pitted gear teeth lock in place, orange with rust but still teaching the shape of motion.",
     0, 0, 7, 7},
    {14, "ladder",             "Ladder",
     "A rough ladder with polished rungs where many hands have trusted it more than they should.",
     0, 0, 6, 7},
    {15, "rope_pulley",        "Rope Pulley",
     "Frayed rope loops through a grooved wheel; one hard pull would tell you what age has left intact.",
     0, 0, 5, 7},
    {16, "ancient_gate",       "Ancient Gate",
     "Weathered stone frames a threshold whose carvings make entry feel like an agreement.",
     0, 0, 20, 7},
    {17, "stone_carvings",     "Stone Carvings",
     "The carvings repeat crowns, rivers, and a ringed sky motif worn soft by years of rain.",
     0, 0, 12, 7},
    {18, "moss_covered_stone", "Moss-Covered Stone",
     "Cool moss softens the old stone, hiding chips and shallow marks beneath green velvet.",
     0, 0, 10, 7},
    {19, "stone_altar",        "Stone Altar",
     "A low stone altar darkened by weather, offerings, and the kind of silence people leave behind.",
     0, 0, 16, 7},
    {20, "ancient_symbols",    "Ancient Symbols",
     "The symbols lean toward meaning without giving it up; each line feels deliberate.",
     0, 0, 1, 7},
    {21, "moss",               "Moss",
     "Soft moss grows in irregular patches, bright where water lingers and dark where feet avoid it.",
     0, 0, 1, 7},
    {22, "standing_stones",    "Standing Stones",
     "The stones stand in a loose ring, each angled as if listening to a different part of the sky.",
     0, 0, 22, 7},
    {23, "ancient_artifacts",  "Ancient Artifacts",
     "Small relics rest together: cracked charms, worked metal, and fragments with more history than use.",
     0, 0, 4, 7},
    {24, "magical_items",      "Magical Items",
     "These curios hum at the edge of attention, more suggestive than obedient.",
     0, 0, 3, 7},
    {25, "rare_curiosities",   "Rare Curiosities",
     "Odd little treasures from distant shelves invite questions before they invite prices.",
     0, 0, 3, 7},
    {26, "chest",              "Chest",
     "A sturdy chest with enough presence to deserve its own little problem.",
     0, 0, 12, 7},
    {27, "dust_sheet",         "Dust Sheet",
     "A grey sheet hangs over old shapes, turning furniture into ghosts with corners.",
     0, 0, 2, 7},
    {28, "swing",              "Swing",
     "A simple rope swing creaks in the breeze, its seat polished by absent afternoons.",
     0, 0, 4, 7},
    {29, "vegetable_garden",   "Vegetable Garden",
     "Rows of practical green growth mark someone's steady campaign against hunger.",
     0, 0, 8, 7},
    {30, "wildflowers",        "Wildflowers",
     "Wildflowers scatter color through the grass with no concern for borders or ownership.",
     0, 0, 1, 7},
    {31, "bread",              "Bread",
     "A crust split along the top remembers heat; the crumb inside stays honest.",
     0, 0, 1, 7},
    {32, "fresh_bread",        "Fresh Bread",
     "Still faintly warm at the core if you lean close enough to pretend kitchens exist.",
     0, 0, 1, 7},
    {33, "cheese",             "Cheese",
     "Waxy rind, salty edge; someone carved patience into dairy.",
     0, 0, 1, 7},
    {34, "stew",               "Stew",
     "Oil gleams on the surface where spices argued and carrots surrendered.",
     0, 0, 2, 7},
    {35, "flour",              "Flour",
     "Fine dust that coats sleeves and ambitions alike.",
     0, 0, 1, 7},
    {36, "lockpick",           "Lockpick",
     "A slender bend of metal tuned more for patience than pride.",
     0, 0, 1, 7},
    {37, "torch",              "Torch",
     "Pitch-dark wraps tarred cloth; the flame will argue with drafts.",
     0, 0, 2, 7},
    {38, "bucket",             "Bucket",
     "Rim worn dull where hands grabbed urgency instead of care.",
     0, 0, 3, 7},
    {39, "gold_coin",          "Gold Coin",
     "Weight enough to believe in trade and trouble.",
     0, 0, 1, 7},
    {40, "scrap_metal",        "Scrap Metal",
     "Twisted pieces still dreaming of being tools.",
     0, 0, 4, 7},
    {41, "wood_scrap",         "Wood Scrap",
     "Splinters bundled into usefulness through stubborn optimism.",
     0, 0, 3, 7},
    {42, "waterskin",          "Waterskin",
     "Soft leather sweats a little; thirst trusts it anyway.",
     0, 0, 2, 7},
    {43, "eggs",               "Eggs",
     "Smooth shells hide futures that crack open too honest for polite mornings.",
     0, 0, 1, 7},
    {44, "rations",            "Rations",
     "Wrapped tight against hunger and optimism in equal measure.",
     0, 0, 2, 7},
    {45, "fish",               "Fish",
     "Scales catch light like proof something lived outside your schedule.",
     0, 0, 2, 7},
    {46, "dried_meat",         "Dried Meat",
     "Salt and patience turned muscle into something that survives travel.",
     0, 0, 2, 7},
    {47, "roasted_meat",       "Roasted Meat",
     "Char at the edges argues with smoke about how civilization tastes.",
     0, 0, 2, 7},
    {48, "meat",               "Meat",
     "Raw promise that kitchens negotiate into meals.",
     0, 0, 2, 7},
    {49, "fancy_cakes",        "Fancy Cakes",
     "Sugar architecture built for occasions louder than appetite.",
     0, 0, 2, 7},
    {50, "coffee_beans",       "Coffee Beans",
     "Oils bead on the roast where ambition learns punctuality.",
     0, 0, 1, 7},
    {51, "ale",                "Ale",
     "Foam leans over the rim like an opinion.",
     0, 0, 2, 7},
    {52, "wine",               "Wine",
     "Glass-dark liquid pretending manners until you tilt it.",
     0, 0, 2, 7},
    {53, "wine_bottle",        "Wine Bottle",
     "Cobweb glass hides the vintage behind cork and courage.",
     0, 0, 3, 7},
    {54, "old_wine",           "Old Wine",
     "Dust on the label argues age equals virtue.",
     0, 0, 2, 7},
    {55, "mead",               "Mead",
     "Honey surrendered to fermentation with cheerful casualties.",
     0, 0, 2, 7},
    {56, "stream_water",       "Stream Water",
     "Cold clarity from somewhere upstream of your excuses.",
     0, 0, 2, 7},
    {57, "clear_water",        "Clear Water",
     "Nothing in it apologizes for being basic.",
     0, 0, 2, 7},
    {58, "dark_water",         "Dark Water",
     "Depth hides color the way doubt hides intent.",
     0, 0, 2, 7},
    {59, "stick",              "Stick",
     "Straight enough to argue it's useful; crooked enough to be honest.",
     0, 0, 2, 7},
    {60, "reed",               "Reed",
     "Hollow stems bend instead of breaking — philosophy with cellulose.",
     0, 0, 1, 7},
    {61, "hardwood_branch",    "Hardwood Branch",
     "Dense grain fights your grip where softer wood would surrender.",
     0, 0, 4, 7},
    {62, "metal_rod",          "Metal Rod",
     "Cold weight promises leverage more than comfort.",
     0, 0, 5, 7},
    {63, "flint",              "Flint",
     "A gray chip that dares steel to meet it and lose.",
     0, 0, 1, 7},
    {64, "sharp_stone",        "Sharp Stone",
     "A worked edge that prefers work to debate.",
     0, 0, 1, 7},
    {65, "vine",               "Vine",
     "Green tenacity you can bind with or be bound by.",
     0, 0, 1, 7},
    {66, "leather_cord",       "Leather Cord",
     "Tough strip cut for ties that outlast promises.",
     0, 0, 1, 7},
    {67, "grass_fiber",        "Grass Fiber",
     "Bundled rough threads for small ties and patient repairs.",
     0, 0, 1, 7},
    {68, "long_stick",         "Long Stick",
     "Extra reach for prodding, prying, or pretending you planned ahead.",
     0, 0, 3, 7},
    {69, "bone_shard",         "Bone Shard",
     "A pale splinter with an edge that predates politeness.",
     0, 0, 1, 7},
    {70, "stone_blade",        "Stone Blade",
     "Flaked flint with a mean profile and a short temper.",
     0, 0, 2, 7},
    {71, "iron_spike",         "Iron Spike",
     "Purpose-built for piercing excuses and timber alike.",
     0, 0, 2, 7},
    {72, "leather_wrap",       "Leather Wrap",
     "Supple strip meant for grip, binding, or quiet reassurance.",
     0, 0, 1, 7},
    {73, "bone-tipped_spear",  "Bone-Tipped Spear",
     "Haft and bone point agree that distance solves arguments.",
     0, 0, 5, 7},
    {74, "mailbox",            "Mailbox",
     "Paint flakes off dented metal; the flag remembers mail that never arrived.",
     0, 0, 6, 7},
    {75, "rusty_pick",         "Rusty Pick",
     "Corroded point that still bites stone and cheap locks; bends fast if you bully it.",
     0, 0, 5, 7},
    {76, "iron_ingot",         "Iron Ingot",
     "A heavy brick of worked iron that trades patience for leverage.",
     0, 0, 8, 7},
    {77, "steel_ingot",        "Steel Ingot",
     "Cleaner grain than raw iron; smiths read futures in its gray shine.",
     0, 0, 9, 7},
    {78, "leather_strip",      "Leather Strip",
     "Cut long for straps, bindings, and quiet repairs.",
     0, 0, 1, 7},
    {79, "metal_scrap",        "Metal Scrap",
     "Odd curls of metal saved from worse mistakes.",
     0, 0, 3, 7},
    {80, "whetstone",          "Whetstone",
     "Fine grit that argues dull edges into manners.",
     0, 0, 2, 7},
    {81, "wheat",              "Wheat",
     "Golden heads heavy with the polite conspiracy of bread.",
     0, 0, 2, 7},
    {82, "corn",               "Corn",
     "Tight kernels along the cob like polite spectators.",
     0, 0, 2, 7},
    {83, "potatoes",           "Potatoes",
     "Earth-shaped patience you can roast into proof.",
     0, 0, 2, 7},
    {84, "carrots",            "Carrots",
     "Orange roots that crunch like decisions made outdoors.",
     0, 0, 1, 7},
    {85, "milk",               "Milk",
     "Cool sweetness that remembers barns and steady hands.",
     0, 0, 2, 7},
    {86, "wool",               "Wool",
     "Springy locks spun from weather and sheep optimism.",
     0, 0, 2, 7},
    {87, "chicken",            "Chicken",
     "Feathers and protest in one portable package.",
     0, 0, 4, 7},
    {88, "rope",               "Rope",
     "Twisted fiber trained to trust knots more than people.",
     0, 0, 3, 7},
    {89, "lantern",            "Lantern",
     "Brass frame, clear panels, a fresh-seeming wick; lit, it trades shadow for a warm, "
     "stubborn glow.",
     0, 0, 4, 7},
    {90, "flint_and_steel",    "Flint and Steel",
     "Two stubborn solids that argue until sparks win.",
     0, 0, 2, 7},
    {91, "backpack",           "Backpack",
     "Straps and canvas promise distance from home.",
     0, 0, 5, 7},
    {92, "blanket",            "Blanket",
     "Heavy weave against cold that refuses to negotiate.",
     0, 0, 4, 7},
    {93, "silk_rope",          "Silk Rope",
     "Smooth cord that costs pride as much as coin.",
     0, 0, 3, 7},
    {94, "massage_oil",       "Massage Oil",
     "Warmed scent trapped in oil meant for hands that behave.",
     0, 0, 2, 7},
    {95, "fine_wine",          "Fine Wine",
     "Cork and cellar patience condensed into a dignified pour.",
     0, 0, 2, 7},
    {96, "bandage",            "Bandage",
     "Clean cloth strips pretending wounds listen to reason.",
     0, 0, 1, 7},
    {97, "herbs",              "Herbs",
     "Bundled stems that smell like kitchens and caution.",
     0, 0, 1, 7},
    {98, "salt",               "Salt",
     "Crystals that make flavor honest whether food agrees or not.",
     0, 0, 1, 7},
    {99, "sugar",              "Sugar",
     "Sweet grit that dissolves arguments on the tongue.",
     0, 0, 1, 7},
    {100, "sparkling_wine",    "Sparkling Wine",
     "Tiny bubbles rise like gossip toward the cork.",
     0, 0, 2, 7},
    {101, "herbal_tea",       "Herbal Tea",
     "Steam carries mint and apology in equal measure.",
     0, 0, 1, 7},
    {102, "rose_petal_jam",   "Rose Petal Jam",
     "Sugar and petals reduced until romance becomes spreadable.",
     0, 0, 2, 7},
    {103, "broken_armor",     "Broken Armor",
     "Dented plates that remember impact better than pride.",
     0, 0, 8, 7},
    {104, "broken_weapon",    "Broken Weapon",
     "Snapped steel or split haft — scholarship for a smith.",
     0, 0, 6, 7},
    {105, "iron_ore",         "Iron Ore",
     "Rough stone flecked with rust promises worth the sweat.",
     0, 0, 6, 7},
    {106, "pink_egg",         "Pink Egg",
     "An egg wearing an unlikely blush; best not to ask too loudly.",
     0, 0, 1, 7},
    {107, "blue_egg",         "Blue Egg",
     "Shell the color of sky disagreements — still only breakfast inside.",
     0, 0, 1, 7},
    {108, "purple_egg",       "Purple Egg",
     "Regal shell tint that outruns barnyard modesty.",
     0, 0, 1, 7},
    {109, "fresh_milk",       "Fresh Milk",
     "Cool sweetness still gossiping about the cow.",
     0, 0, 2, 7},
    {110, "bacon_strips",     "Bacon Strips",
     "Salt and smoke folded into strips of temptation.",
     0, 0, 2, 7},
    {111, "room_key",         "Room Key",
     "Brass teeth that rent silence behind a numbered door.",
     0, 0, 1, 7},
    {112, "meal",             "Meal",
     "Bread, stew, or plates — proof someone still tends hunger.",
     0, 0, 3, 7},
    /* Foyer props: web edition this.items (table / coat_rack / mirror) — fills catalog fallback
     * in content_item_response when no bespoke branch exists (house_key and book already do). */
    {113, "table",            "Table",
     "An old wooden surface filmed with dust; rings and scratches map meals that outlasted their guests.",
     0, 0, 12, 7},
    {114, "coat_rack",        "Coat Rack",
     "Pegs and a shallow shelf hold the silhouette of coats stepped out of long ago.",
     0, 0, 6, 7},
    {115, "mirror",           "Mirror",
     "Small glass in a worked frame — clear enough to return your face without commentary.",
     0, 0, 2, 7},
    /* Living room (web living_room item set + same room description in world blurbs) */
    {116, "armchair",         "Armchair",
     "A comfortable corpse of upholstery: splits at the seams, stuffing honest about "
     "how long no one has sat here.",
     0, 0, 10, 7},
    {117, "coffee_table",     "Coffee Table",
     "Low wood scored by water rings and impatience; an empty vase still circles the "
     "same stain.",
     0, 0, 10, 7},
    {118, "vase",             "Vase",
     "Cool ceramic, empty — the kind of vessel that waits for flowers or excuses.",
     0, 0, 3, 7},
    {119, "bookshelf",        "Bookshelf",
     "Shelves of cracked spines and dust; titles lean together like tired soldiers.",
     0, 0, 14, 7},
    {120, "fireplace",        "Fireplace",
     "Stone hearth and carved mantel filmed with dust; cold ash, no flame — only the "
     "memory of heat.",
     0, 0, 18, 7},
    {121, "old_rug",          "Old Rug",
     "A Persian rug worn pale where feet refused to walk around the pattern.",
     0, 0, 8, 7},
    {122, "curtains",         "Curtains",
     "Fabric once proud, now gray-beige and tired; light leaks past like an apology.",
     0, 0, 4, 7},
    /* Garden / approach (web this.items) */
    {123, "fountain",         "Fountain",
     "Stone bowl and low murmur of water — clear enough to trust for a drink or a "
     "wish, depending on your mood.",
     0, 0, 16, 7},
    {124, "gate",             "Gate",
     "Iron gone dull with rust; beyond it, stone hints at steps and a cellar's breath.",
     0, 0, 14, 7},
    /* Kitchen (web inside_house kitchen item list; room blurb in world_generated) */
    {125, "stove",            "Stove",
     "Cast iron gone soft with age; the kind of stove that remembers every winter it "
     "refused to quit.",
     0, 0, 25, 7},
    {126, "sink",             "Sink",
     "Stone basin and slow drain; cold rings where pots rested and hands hurried.",
     0, 0, 12, 7},
    {127, "cupboards",        "Cupboards",
     "Doors on loose hinges; some hang open as if the room exhaled its pantry long ago.",
     0, 0, 10, 7},
    {128, "butcher_block",    "Butcher Block",
     "Thick wood scarred by knives and onions; the honest altar of a working kitchen.",
     0, 0, 14, 7},
    {129, "drying_herbs",     "Drying Herbs",
     "Bundles hung from rafters — rustle like whispered recipes when the air moves.",
     0, 0, 3, 7},
    {130, "pots",             "Pots",
     "Copper and iron stacked with the patience of things that boil for a living.",
     0, 0, 8, 7},
    {131, "pans",             "Pans",
     "Skillets and saucepans cooled to silence; grease ghosts mark the best ones.",
     0, 0, 6, 7},
    /* Library / study (web library room item list + world blurb) */
    {132, "bookshelves",      "Bookshelves",
     "Floor-to-ceiling shelves; ladders lean in like polite excuses to climb toward dust.",
     0, 0, 18, 7},
    {133, "reading_lamp",     "Reading Lamp",
     "A small honest lamp — enough cone of light to pretend the rest of the room stops.",
     0, 0, 3, 7},
    {134, "reading_nook",     "Reading Nook",
     "A pocket of chair and shadow where drafts carry the smell of old paper.",
     0, 0, 9, 7},
    /* Simple inn / guest props (world lists; web uses similar bedroom vocabulary) */
    {135, "bed",              "Bed",
     "Frame and mattress holding the hollow shape of sleep; linens forget their color.",
     0, 0, 14, 7},
    {136, "window",           "Window",
     "Glass filmed or boarded; light negotiates its way in on someone else's terms.",
     0, 0, 8, 7},
    /* Dining room (web dining_room items + room blurb) */
    {137, "dining_table",     "Dining Table",
     "A long plank of oak meant for twelve; dust has claimed the polish, but the grain "
     "still remembers feasts.",
     0, 0, 20, 7},
    {138, "chairs",           "Chairs",
     "High-backed seats in a patient circle, wood dry and honest — waiting for guests who "
     "never came back.",
     0, 0, 12, 7},
    {139, "place_settings",   "Place Settings",
     "Plates, forks, and cloudy glass arranged like a rehearsal; silver tarnish is the "
     "only guest left.",
     0, 0, 10, 7},
    {140, "chandelier",       "Chandelier",
     "Crystal prisms gone smoky; when a draft moves, they argue in dull sparks overhead.",
     0, 0, 18, 7},
    {141, "sideboard",        "Sideboard",
     "A long cabinet for pride and leftovers; empty serving dishes crowd tarnished "
     "silver behind glass doors.",
     0, 0, 14, 7},
    {142, "silverware",       "Silverware",
     "Forks and spoons dulled to pewter honesty; someone polished these once with "
     "stubborn love.",
     0, 0, 8, 7},
    {143, "portraits",        "Portraits",
     "Stern ancestors in gilt frames — eyes that follow you the way guilt follows a "
     "footstep.",
     0, 0, 22, 7},
    /* Pantry (web pantry) */
    {144, "empty_jars",       "Empty Jars",
     "Glass soldiers on a shelf, labels peeled; a few still smell faintly of fruit that "
     "is long gone.",
     0, 0, 6, 7},
    {145, "preserved_foods",  "Preserved Foods",
     "Jars with stubborn color at the bottom — jam or pickles, sealed against time with "
     "mixed success.",
     0, 0, 4, 7},
    {146, "storage_containers", "Storage Containers",
     "Tins and bins stacked like a quiet apology for hunger; most hold only air and "
     "cool dust.",
     0, 0, 5, 7},
    {147, "shelves",          "Shelves",
     "Bare wood and nail holes; the pantry exhaled its stores and kept the skeleton.",
     0, 0, 14, 7},
    /* Bedroom hallway (web bedroom_hallway) */
    {148, "hallway_window",   "Hallway Window",
     "A narrow pane at the hall's end; the garden outside looks gentler through dust and "
     "old putty.",
     0, 0, 8, 7},
    {149, "door_frames",      "Door Frames",
     "Paint chipped along the jambs; each threshold is a small treaty between rooms.",
     0, 0, 10, 7},
    /* Master bedroom (web master_bedroom) */
    {150, "four_poster_bed",  "Four-Poster Bed",
     "Turned posts and a canopy of faded cloth; the mattress holds a hollow where sleep "
     "used to live.",
     0, 0, 16, 7},
    {151, "bed_curtains",     "Bed Curtains",
     "Heavy drapes drawn back in defeat; they still smell of perfume and stale linen.",
     0, 0, 12, 7},
    {152, "wardrobe",         "Wardrobe",
     "A tall cabinet with a mirror door that lies politely; hangers clink when the house "
     "breathes.",
     0, 0, 14, 7},
    {153, "vanity_table",     "Vanity Table",
     "A small stage for brushes and bottles — most missing, a few rings marking where "
     "vanity sat.",
     0, 0, 9, 7},
    {154, "personal_items",   "Personal Items",
     "Comb, ribbon, letter corner — the debris of a life that left without packing neatly.",
     0, 0, 7, 7},
    {155, "dresser",          "Dresser",
     "Drawers on stiff runners; one sticks as if hiding a thought worth keeping.",
     0, 0, 11, 7},
    /* Bathrooms (web master_bathroom + shared bathroom) */
    {156, "bathtub",          "Bathtub",
     "Claw feet and porcelain worn thin; the drain gurgles like it remembers every soak.",
     0, 0, 12, 7},
    {157, "towel_rack",       "Towel Rack",
     "Brass gone green at the screws; a single towel ghost hangs stiff as parchment.",
     0, 0, 8, 7},
    {158, "medicine_cabinet", "Medicine Cabinet",
     "Mirrored door and shallow shelves — a few brown bottles, labels curled like "
     "sleeping moths.",
     0, 0, 8, 7},
    {159, "toilet",           "Toilet",
     "Porcelain and chain-pull dignity; the flush is brave but the pipes mutter age.",
     0, 0, 10, 7},
    {160, "shower",           "Shower",
     "A stall of cracked tile and a head that weeps rust; steam ghosts mark the ceiling.",
     0, 0, 8, 7},
    /* Basement (web basement) */
    {161, "old_box",          "Old Box",
     "Wood swollen with damp; whatever it holds has waited in the dark longer than you.",
     0, 0, 4, 7},
    /* Guest bedroom (web guest_bedroom — bed/window already catalogued) */
    {162, "desk",             "Desk",
     "Small writing surface, ink ghost in one corner; a drawer resists as if shy.",
     0, 0, 9, 7},
    {163, "chair",            "Chair",
     "Straight-backed and honest; the cane seat sighs when you look at it too long.",
     0, 0, 8, 7},
    /* Study (web study items — tomes/ledger/lockpick have bespoke examine in ascii) */
    {164, "inkwell",          "Inkwell",
     "A shallow well of ink gone thick at the rim; a ring of old fingerprints judges your "
     "penmanship.",
     0, 0, 2, 7},
    {165, "quill",            "Quill",
     "Barb cleaned to a selfish point; it wants a steady hand and a patient blotter.",
     0, 0, 1, 7},
    {166, "papers",           "Papers",
     "Sheets edged with curl and urgency — maps, tallies, letters half abandoned mid-thought.",
     0, 0, 2, 7},
    {167, "globe",            "Globe",
     "Painted oceans faded to suggestion; continents wear the matte dust of neglected "
     "ambition.",
     0, 0, 5, 7},
    {168, "reading_chair",    "Reading Chair",
     "Wingback leather cracked at the elbows — the shape of someone who read until the "
     "candles complained.",
     0, 0, 14, 7},
    /* Backyard path (web backyard) */
    {169, "stone_path",       "Stone Path",
     "Irregular flags sunk in grass; moss negotiates the joints like a quiet treaty.",
     0, 0, 18, 7},
    /* Shed (web backyard_shed) */
    {170, "rake",             "Rake",
     "Tines rust-freckled; the handle remembers hands that cleared leaves before giving up.",
     0, 0, 5, 7},
    {171, "shovel",           "Shovel",
     "Blade dulled honest by earth; the step plate bows where boots insisted.",
     0, 0, 8, 7},
    {172, "gardening_tools",  "Gardening Tools",
     "Trowels, shears, and odds hung in silhouette — metal that forgot the garden but not "
     "the shed.",
     0, 0, 10, 7},
    {173, "seeds",            "Seeds",
     "Paper packets soft with oil; some rattles promise parsley, others only hope.",
     0, 0, 1, 7},
    /* Forest path (web forest_path) */
    {174, "stone_marker",     "Stone Marker",
     "Weathered rock carved with symbols that refuse a single reading — trail, warning, or "
     "joke.",
     0, 0, 25, 7},
    {175, "fallen_branch",    "Fallen Branch",
     "Bark scaled, heartwood pale; good for a fire, a bridge, or a lesson in humility.",
     0, 0, 6, 7},
    /* Deep forest floor (web deep_forest) */
    {176, "glowing_mushrooms", "Glowing Mushrooms",
     "Caps lit with a sickly patience; they paint the loam in coin-sized constellations.",
     0, 0, 2, 7},
    {177, "fallen_leaves",    "Fallen Leaves",
     "A dry tide of oak and pine; each step announces you to things that prefer listening.",
     0, 0, 3, 7},
    {178, "ancient_tree_bark", "Ancient Tree Bark",
     "Plates of bark thick as armor; resin ghosts the air where the trunk was wounded long "
     "ago.",
     0, 0, 4, 7},
    /* Hermit's hut (web hermit_hut) */
    {179, "ancient_tome",     "Ancient Tome",
     "Covers bowed under their own seriousness; the spine crackles like a warning label.",
     0, 0, 8, 7},
    {180, "herb_bundle",      "Herb Bundle",
     "Twine-bound stems still arguing about mint, sage, and something sharper underneath.",
     0, 0, 2, 7},
    {181, "mysterious_artifact", "Mysterious Artifact",
     "Metal and stone in a shape that suggests function without confessing it — small "
     "enough to steal, heavy enough to doubt.",
     0, 0, 3, 7},
    /* Meadow (web meadow) */
    {182, "butterflies",      "Butterflies",
     "Wings like torn sunlight; they refuse to sit still long enough to be catalogued.",
     0, 0, 1, 7},
    {183, "tall_grass",       "Tall Grass",
     "Seed heads brush your wrists; the meadow whispers against your boots.",
     0, 0, 4, 7},
    /* Pond (web pond) */
    {184, "water_lilies",     "Water Lilies",
     "Pads and pale blooms asleep on glass; the water keeps their secrets without ripples.",
     0, 0, 3, 7},
    {185, "reeds",            "Reeds",
     "Tall stems knit at the bank; wind turns them into one slow breath.",
     0, 0, 5, 7},
    {186, "wooden_dock",      "Wooden Dock",
     "Planks gray and nail-sick; it extends faith over depth you cannot quite see.",
     0, 0, 20, 7},
    /* Stream (web stream — stream_water/fish already catalogued) */
    {187, "smooth_stones",    "Smooth Stones",
     "Rounds worn by patience; cold through the fingers and honest about the current.",
     0, 0, 8, 7},
    /* Stream source (web stream_source) */
    {188, "natural_spring",   "Natural Spring",
     "Water rises clear and rude with cold; ferns lean in to steal the chill.",
     0, 0, 12, 7},
    {189, "waterfall",        "Waterfall",
     "A small fall that still sounds like an argument between stone and gravity.",
     0, 0, 15, 7},
    {190, "ferns",            "Ferns",
     "Fronds uncurl in the spray's gossip; green that refuses to apologize for damp.",
     0, 0, 3, 7},
    /* Hilltop (web hilltop) */
    {191, "boulder",          "Boulder",
     "A seat for the wind; lichen maps continents you could cross in a lazy afternoon.",
     0, 0, 40, 7},
    {192, "wild_grasses",     "Wild Grasses",
     "Blades lean together like a crowd pretending not to watch the view.",
     0, 0, 4, 7},
    {193, "viewpoint",        "Viewpoint",
     "Air thins and brightens; the house, the forest, and the village arrange themselves "
     "without asking.",
     0, 0, 2, 7},
    /* Rocky outcrop (web rocky_outcrop) */
    {194, "boulders",         "Boulders",
     "Tumbled giants shoulder to shoulder; animal paths thread the gaps like polite "
     "afterthoughts.",
     0, 0, 35, 7},
    {195, "lichen",           "Lichen",
     "Pale maps on stone — slow life that outlasts the names people give hills.",
     0, 0, 2, 7},
    {196, "rock_crevices",    "Rock Crevices",
     "Shadowed splits that hoard grit, seed, and the occasional nervous skitter.",
     0, 0, 6, 7},
    /* Cave approach & interior (web cave_entrance / cave_interior) */
    {197, "overgrown_vegetation", "Overgrown Vegetation",
     "Bramble and vine claiming the mouth — the cave inhales past them anyway.",
     0, 0, 8, 7},
    {198, "cave_opening",     "Cave Opening",
     "A dark comma in the hillside; cool breath slips out like a patient invitation.",
     0, 0, 10, 7},
    {199, "stalactites",      "Stalactites",
     "Stone teeth depending from the roof; each drip is a small, stubborn clock.",
     0, 0, 12, 7},
    {200, "water_pool",       "Water Pool",
     "Still water in a stone cup; your reflection arrives late and leaves early.",
     0, 0, 14, 7},
    {201, "glowing_crystals", "Glowing Crystals",
     "Facets hoard a sickly glow; they light the wall like buried stars trying to surface.",
     0, 0, 5, 7},
    {202, "stone_formations", "Stone Formations",
     "Flow and fold frozen mid-thought — geology pretending to be sculpture.",
     0, 0, 16, 7},
    /* Deep cave (web cave_deep) */
    {203, "ancient_markings", "Ancient Markings",
     "Carved lines repeat until pattern feels like pressure; the wall insists on being "
     "read.",
     0, 0, 8, 7},
    {204, "more_crystals",    "More Crystals",
     "A denser choir of glow — enough light to pretend you are not trespassing.",
     0, 0, 6, 7},
    {205, "hidden_chamber",   "Hidden Chamber",
     "Air changes here — tighter, older — as if space learned to hold its breath.",
     0, 0, 3, 7},
    /* Old well & garden shed (web old_well / shed) */
    {206, "well_bucket",      "Well Bucket",
     "Rust and oak staves; rope frayed where hands worried it on the way up from darkness.",
     0, 0, 6, 7},
    {207, "tools",            "Tools",
     "Handles and heads in a democratic pile — each one argues it is essential.",
     0, 0, 12, 7},
    {208, "tension_wrench",   "Tension Wrench",
     "A slim bar for torque and patience; lockwork respects it more than muscle.",
     0, 0, 1, 7},
    /* Hollow Ridge — village road & tavern (web village_road … tavern_privy) */
    {209, "roadside_stone",   "Roadside Stone",
     "A low marker rubbed smooth by cart wheels; mud dries in the letters of old directions.",
     0, 0, 20, 7},
    {210, "hitching_post",    "Hitching Post",
     "Iron ring and splintered post; leather ghosts the wood where reins sawed in the wind.",
     0, 0, 12, 7},
    {211, "bar",              "Bar",
     "Long plank scarred by mugs and elbows; bottles rank behind like a skeptical choir.",
     0, 0, 25, 7},
    {212, "barstool",         "Barstool",
     "Round seat on a wobbling leg — honest about how the night will end.",
     0, 0, 6, 7},
    {213, "mug",              "Mug",
     "Glazed ceramic thick enough to survive temper; a ring of old foam remembers the last pour.",
     0, 0, 2, 7},
    {214, "tables",           "Tables",
     "Scuffed rounds and trestles; knife marks map conversations that outlasted the speakers.",
     0, 0, 18, 7},
    {215, "hearth",           "Hearth",
     "Stone throat full of last night's heat; ash fine enough to write temporary truths.",
     0, 0, 30, 7},
    {216, "cooking_pot",      "Cooking Pot",
     "Black iron with a patient belly; steam ghosts the rafters when something worth waiting "
     "for boils.",
     0, 0, 10, 7},
    {217, "spit",             "Spit",
     "Iron skewer and grease drip — theater for anyone who claims they are not hungry.",
     0, 0, 8, 7},
    {218, "prep_table",       "Prep Table",
     "Flour dust and onion skin; the board remembers every chop that hurried before service.",
     0, 0, 22, 7},
    {219, "flour_barrel",     "Flour Barrel",
     "Hoops rust-flecked; tap the staves and a soft white cough answers.",
     0, 0, 18, 7},
    {220, "salt_barrel",      "Salt Barrel",
     "Crystals rasp when the scoop dives; the kitchen's quiet argument with blandness.",
     0, 0, 16, 7},
    {221, "ale_barrel",       "Ale Barrel",
     "Oak breathing slow fermentation; the bung smells like patience and bad decisions.",
     0, 0, 22, 7},
    {222, "wine_barrel",      "Wine Barrel",
     "Darker stain at the bilge; roll it and something expensive sloshes like a secret.",
     0, 0, 22, 7},
    {223, "pickled_vegetables", "Pickled Vegetables",
     "Jars of vinegar bravado — cabbage and beet that refused to rot on principle.",
     0, 0, 4, 7},
    {224, "dried_meat",       "Dried Meat",
     "Strips gone leather-honest; salt and smoke argue on the tongue.",
     0, 0, 3, 7},
    {225, "comfortable_chairs", "Comfortable Chairs",
     "Wingbacks dragged into conspiracy; the upholstery keeps scores of hushed deals.",
     0, 0, 14, 7},
    {226, "old_maps",         "Old Maps",
     "Vellum curled at the coasts; ink harbors islands that politics forgot.",
     0, 0, 3, 7},
    {227, "nautical_artifacts", "Nautical Artifacts",
     "Knot boards, glass floats, a harpoon tip dulled to ornament — the sea translated into "
     "trophy.",
     0, 0, 8, 7},
    {228, "candles",          "Candles",
     "Tapers and stubs; wax drips record hours the lantern refused to count.",
     0, 0, 2, 7},
    {229, "private_table",    "Private Table",
     "Single plank for two chairs and a heavy door — geometry built for deniability.",
     0, 0, 14, 7},
    {230, "tapestries",       "Tapestries",
     "Woven battles and ships; moth has edited the glory down to suggestion.",
     0, 0, 12, 7},
    {231, "number_plates",    "Number Plates",
     "Small brass tags above each door — modest integers guarding loud nights.",
     0, 0, 1, 7},
    {232, "straw_mattress",   "Straw Mattress",
     "Rustle and poke; honesty in bedding — you will know morning when it finds you.",
     0, 0, 12, 7},
    {233, "washbasin",        "Washbasin",
     "Porcelain bowl on a stand; rings of soap like old moons.",
     0, 0, 6, 7},
    {234, "comfortable_mattress", "Comfortable Mattress",
     "Thicker tick and fewer lectures; the inn charges for the difference.",
     0, 0, 16, 7},
    {235, "writing_desk",     "Writing Desk",
     "Ink scar in one corner; a drawer sticks on a letter someone thought better of.",
     0, 0, 10, 7},
    {236, "balcony",          "Balcony",
     "Narrow rail over the alley; air tastes of smoke, rain, and someone else's songs.",
     0, 0, 2, 7},
    {237, "horse_stalls",     "Horse Stalls",
     "Timber boxes and straw floors; breath and hoof scrape compose the stable's music.",
     0, 0, 14, 7},
    {238, "hay",              "Hay",
     "Gold dust and stems; every sneeze is a vote for the country.",
     0, 0, 6, 7},
    {239, "tack",             "Tack",
     "Bridles, bits, and sweat-polished leather — metal that learned gentleness.",
     0, 0, 8, 7},
    {240, "barrels",          "Barrels",
     "Stacked promises of ale, rain, or neglect; hoops groan when you lean.",
     0, 0, 16, 7},
    {241, "crates",           "Crates",
     "Slatted wood and stencil marks; something inside shifts when you pretend not to listen.",
     0, 0, 14, 7},
    {242, "delivery_door",    "Delivery Door",
     "Back entrance, honest hinges; grease and flour argue on the jamb.",
     0, 0, 10, 7},
    {243, "privy_seat",       "Privy Seat",
     "Pine worn smooth by necessity; the latch is the room's entire diplomacy.",
     0, 0, 8, 7},
    {244, "latch",            "Latch",
     "Iron tongue and shy slot — small mechanics of dignity.",
     0, 0, 1, 7},
    {245, "well",             "Well",
     "Stone lip and rope groove; your voice returns smaller from the dark.",
     0, 0, 18, 7},
    {246, "market_stall",     "Market Stall",
     "Canvas roof and plank counter — a stage where cabbage plays hero.",
     0, 0, 15, 7},
    {247, "inn_table",        "Inn Table",
     "Scrubbed oak that knows bread and gossip in equal measure.",
     0, 0, 14, 7},
    {248, "inn_chair",        "Inn Chair",
     "Spindle back, seat hollowed by honest sitting.",
     0, 0, 8, 7},
    /* Temple & farm (web temple_of_architect … farm) */
    {249, "altar",            "Altar",
     "Marble cool as a held breath; cloth and smoke argue about holiness.",
     0, 0, 20, 7},
    {250, "incense_burner",   "Incense Burner",
     "Brass lattice and gray ash; scent stacks in layers until thought slows.",
     0, 0, 4, 7},
    {251, "prayer_cushions",  "Prayer Cushions",
     "Velvet flattened by knees; each dent is a private conversation.",
     0, 0, 6, 7},
    {252, "holy_symbols",     "Holy Symbols",
     "Carved and gilded lines that repeat until the eye accepts pattern as comfort.",
     0, 0, 3, 7},
    {253, "flowers",          "Flowers",
     "Bedded color with bee traffic; petals bruise if you rush them.",
     0, 0, 2, 7},
    {254, "meditation_bench", "Meditation Bench",
     "Low wood facing water; the grain invites stillness without promising it.",
     0, 0, 10, 7},
    {255, "weapon_rack",      "Weapon Rack",
     "Pegs and iron hooks; steel sleeps here in disciplined rows.",
     0, 0, 12, 7},
    {256, "training_dummy",   "Training Dummy",
     "Sack and leather pretend a torso; straw leaks where mercy was practiced.",
     0, 0, 14, 7},
    {257, "practice_weapons", "Practice Weapons",
     "Blunted edges and wrapped hilts — violence taught to whisper.",
     0, 0, 10, 7},
    {258, "wheat_field",      "Wheat Field",
     "Gold heads bowing in ranks; wind turns the field into slow applause.",
     0, 0, 4, 7},
    {259, "corn_field",       "Corn Field",
     "Stiff stalks and silk tassels; crows negotiate from the margins.",
     0, 0, 5, 7},
    {260, "chicken_coop",     "Chicken Coop",
     "Wire and feather dust; the door latch sounds like small outrage.",
     0, 0, 12, 7},
    {261, "cow_pen",          "Cow Pen",
     "Rails and churned mud; warm breath greets you at nose height.",
     0, 0, 14, 7},
    /* Village commerce & forge (web general_store, blacksmith) */
    {262, "store_counter",    "Store Counter",
     "Polished grain and a bell's ghost; commerce begins at the edge of this plank.",
     0, 0, 18, 7},
    {263, "display_case",     "Display Case",
     "Glass and brass frame small treasures; fingerprints judge your restraint.",
     0, 0, 12, 7},
    {264, "hammer",           "Hammer",
     "Head heavy with opinion; the handle knows your wrist better than you do.",
     0, 0, 5, 7},
    {265, "tongs",            "Tongs",
     "Forged jaws for holding heat at arm's length — respect in iron.",
     0, 0, 3, 7},
    {266, "water_trough",     "Water Trough",
     "Stone or timber long enough for steam to die; rings mark where metal cooled.",
     0, 0, 20, 7},
    /* Forest secrets & cellar (web forest_clearing, hidden_grove, hidden_cellar) */
    {267, "altar_stone",      "Altar Stone",
     "Moss-choked slab; runes hold a pulse the forest pretends not to notice.",
     0, 0, 25, 7},
    {268, "journal",          "Journal",
     "Leather soft with sweat; pages curl where weather got there first.",
     0, 0, 2, 7},
    {269, "mysterious_gem",   "Mysterious Gem",
     "Facet catches light it did not borrow; holding it warms the palm without excuse.",
     0, 0, 1, 7},
    {270, "rare_herbs",       "Rare Herbs",
     "Leaves that smell like questions; sap stains your fingers with privilege.",
     0, 0, 2, 7},
    {271, "ancient_tree",     "Ancient Tree",
     "Bark in plates older than the path; roots drink patience from deep silence.",
     0, 0, 30, 7},
    {272, "dusty_jars",       "Dusty Jars",
     "Glass under fur; labels faded into rumor.",
     0, 0, 5, 7},
    /* Swamp (web swamp_clearing … swamp_island) */
    {273, "bog_fungi",        "Bog Fungi",
     "Shelves of damp color; spores tickle the throat like bad advice.",
     0, 0, 2, 7},
    {274, "twisted_root",     "Twisted Root",
     "Knobbed wood surfaced from the muck; grips like something trying to climb out.",
     0, 0, 6, 7},
    {275, "rotten_plank",     "Rotten Plank",
     "Boardwalk honesty — spongy heartwood and a creak that votes no.",
     0, 0, 5, 7},
    {276, "marsh_gas",        "Marsh Gas",
     "Shimmer above black water; the swamp lights its own unreliable lamps.",
     0, 0, 1, 7},
    {277, "mysterious_shovel", "Mysterious Shovel",
     "Blade dark with peat; the handle remembers hands that dug for more than turnips.",
     0, 0, 8, 7},
    /* Ridge & hollow cave (web hollow_ridge, hollow_ridge_cave); hillside path_markers */
    {278, "weathered_stone",  "Weathered Stone",
     "Ridge bones scoured by wind; tool marks argue with rain.",
     0, 0, 22, 7},
    {279, "ancient_carving",  "Ancient Carving",
     "Lines worn shallow; meaning survives as pressure rather than picture.",
     0, 0, 8, 7},
    {280, "crystal_fragment", "Crystal Fragment",
     "Sharp little honesty of light; fits the pocket like an inconvenient conscience.",
     0, 0, 1, 7},
    {281, "cave_crystal",     "Cave Crystal",
     "Growths on the wall with a pulse you can almost set a watch to.",
     0, 0, 4, 7},
    {282, "ancient_symbol",   "Ancient Symbol",
     "Carved curve and angle; the eye completes the spell whether invited or not.",
     0, 0, 3, 7},
    {283, "clear_water",      "Clear Water",
     "Pool like polished glass; stones on the bottom look closer than they are.",
     0, 0, 12, 7},
    {284, "path_markers",     "Path Markers",
     "Stacked stones and blazes — the trail's polite argument with getting lost.",
     0, 0, 5, 7},
    /* Currency & cash finds */
    {285, "silver_coin",      "Silver Coin",
     "Cool stamp and clipped rim; enough buying power to make you pat your pocket twice.",
     0, 0, 1, 7},
    {286, "bronze_coin",      "Bronze Coin",
     "Small change with working-class mileage rubbed into the face.",
     0, 0, 1, 7},
    {287, "copper_coin",      "Copper Coin",
     "Thin little promise of bread, thread, or one more practical favor.",
     0, 0, 1, 7},
    {288, "ancient_coin",     "Ancient Coin",
     "Older minting, heavier press; history kept its teeth on the edge.",
     0, 0, 1, 7},
    {289, "hidden_cash",      "Hidden Cash",
     "Coins wrapped in old cloth and worry; someone meant to come back for them.",
     0, 0, 1, 7},
    {290, "buried_coin",      "Buried Coin",
     "Soil still clings to the face; luck only counts if you were stubborn enough to dig.",
     0, 0, 1, 7},
};
/* clang-format on */

static int slug_ieq(const char *a, const char *b) {
  unsigned char ca, cb;
  if (!a || !b) return 0;
  while (*a && *b) {
    ca = (unsigned char)*a++;
    cb = (unsigned char)*b++;
    if (tolower(ca) != tolower(cb)) return 0;
  }
  return *a == '\0' && *b == '\0';
}

const AetItemCatalogEntry *aet_item_catalog_by_slug(const char *slug) {
  size_t i;
  if (!slug || !slug[0]) return NULL;
  for (i = 0; i < sizeof CATALOG / sizeof CATALOG[0]; i++) {
    if (slug_ieq(slug, CATALOG[i].slug)) return &CATALOG[i];
  }
  return NULL;
}

const AetItemCatalogEntry *aet_item_catalog_by_id(int id) {
  size_t i;
  if (id < 1) return NULL;
  for (i = 0; i < sizeof CATALOG / sizeof CATALOG[0]; i++) {
    if (CATALOG[i].id == id) return &CATALOG[i];
  }
  return NULL;
}

int aet_item_catalog_count(void) {
  return (int)(sizeof CATALOG / sizeof CATALOG[0]);
}

const char *aet_item_catalog_label_for_slug(const char *slug) {
  const AetItemCatalogEntry *e = aet_item_catalog_by_slug(slug);
  return (e && e->label && e->label[0]) ? e->label : NULL;
}

const char *aet_item_catalog_description_for_slug(const char *slug) {
  const AetItemCatalogEntry *e = aet_item_catalog_by_slug(slug);
  return (e && e->description && e->description[0]) ? e->description : NULL;
}
