#include "aeternitas_mod_guide.h"

const char *aet_mod_guide_full_text(void) {
  return "AETERNITAS64 -- MODDING & DLC CONTENT GUIDE\n"
         "(Arrow keys, PgUp/PgDn, Home/End -- or j/k -- Q/Enter to close)\n"
         "\n"
         "OVERVIEW\n"
         "--------\n"
         "The C/stdin port has no embedded script runtime. Mods are pure data: text files on\n"
         "disk, merged into RAM at startup (or after \"mods reload\"). This is ideal\n"
         "for episodic DLC, seasonal events, translation packs, and licensed add-ons:\n"
         "ship a folder users drop next to their save, or point AETER_MODS at your\n"
         "install directory.\n"
         "\n"
         "PLACEHOLDERS (character/*.txt overlays)\n"
         "----------------------------------------\n"
         "Use %NAME% %RACE% %CLASS% %ROLE% %PRONOUNS% in character overlay files;\n"
         "they expand when the player opens that panel (same tokens as npcs/*.greeting.txt).\n"
         "With a current location, the engine also fills %ROOMTITLE% %ROOMSLUG% %ROOM%\n"
         "(slug) and %REGION%. From the world clock: %TIME% %PERIOD% %DAY% %SEASON%\n"
         "%WEATHER% %TEMPC% (Celsius integer).\n"
         "From play state: %COINS% %HP% %MAXHP% %SCORE% %TURNS% %INVCOUNT%\n"
         "%INVMAX% %PACK% (e.g. 3/128) %READIED%.\n"
         "World progress: %WORLDROOMS% %VISITED% %NOTECOUNT% %EXPLORE% (percent).\n"
         "Character sheet fields: %STR% %AGI% %INT% %WIS% %CHA% %COR% %AGE% %GENDER%\n"
         "%CLASSID% %RACEID% %BUILD% %MUSCLE%.\n"
         "Derived profile fields: %POWER% %RESOLVE% %CUNNING% %PRESENCE% %HPPCT%\n"
         "%RISK% %RISKLABEL% %TEMPER% %ARCHETYPE% %CORTIER% (alias %CORSTATE%).\n"
         "Narrative-tone helpers: %VOICESTYLE% %MORALVECTOR% %THREATPOSTURE%.\n"
         "Scene/state helpers: %SCENETONE% %TRAVELMOOD% %SOCIALSTANCE%.\n"
         "NPC-memory helpers: %NPCHERE% %NPCDISPLAY% %NPCROLE% %NPCDANGER% %NPCTRUST% %NPCLEVERAGE% %NPCPRESENCE%\n"
         "%LASTNPCHERE% %LASTNPCDISPLAY% %LASTNPCROLE% %LASTNPCATTITUDE% %LASTNPCDANGER% %LASTNPCTRUST% %LASTNPCLEVERAGE%.\n"
         "Session: %LASTNPC% %LASTFOCUS% %LASTTOPIC% %LASTTOPICMOOD% %TOPICHEAT% %ROOMMODE% (verbose|brief).\n"
         "\n"
         "FOLDER LAYOUT\n"
         "-------------\n"
         "  <mods root>/\n"
         "    <pack_name>/          one folder per pack (see naming below)\n"
         "      manifest.txt        optional -- priority=, enabled=0, disabled=1,\n"
         "                          id= / title= (shown in  mods list ),\n"
         "                          # comments; skipped packs are not loaded.\n"
         "      rooms/<slug>.txt    replaces full room blurb (slug from world)\n"
         "      rooms/<slug>.prepend.txt / .append.txt -- layer text before/after\n"
         "                          the current blurb (after .txt replaces, per pack)\n"
         "      titles/<slug>.txt   one-line room title shown in UI\n"
         "      items/<id>.txt      examine / read / touch text for that item id\n"
         "      npcs/<entity>.greeting.txt\n"
         "      npcs/<entity>__<keyword>.txt   topic line; keyword matched inside\n"
         "                                      the lowercased talk phrase\n"
         "      character/sheet_append.txt     after compact sheet brief / char brief / "
         "appearance\n"
         "      character/portrait_append.txt  after full character / sheet portrait\n"
         "      character/aptitudes_append.txt after skills / aptitudes fullscreen\n"
         "      character/reputation_append.txt after reputation / rep / standing\n"
         "      character/loadout_append.txt after loadout / gear / equipment\n"
         "      character/traits_append.txt after traits / personality\n"
         "      character/momentum_append.txt after momentum / arc / progression\n"
         "      character/perks_append.txt after perks / perk\n"
         "      character/voice_append.txt after voice / speech / pronouns\n"
         "      character/bio_append.txt after bio / backstory / biography\n"
         "      character/tainting_append.txt after tainting / corruption\n"
         "      character/rapport_append.txt after rapport / relationships / bonds\n"
         "      character/objectives_append.txt after objectives / goals\n"
         "      character/journal_append.txt after journal / quests fullscreen\n"
         "      character/progress_append.txt after progress / visited / seen\n"
         "      character/inventory_append.txt after inventory / inv / pack\n"
         "      character/waypoints_append.txt after waypoints / nexus list\n"
         "      character/status_append.txt after status / stat fullscreen\n"
         "      character/score_append.txt after score fullscreen\n"
         "      character/time_append.txt after time / clock fullscreen\n"
         "      character/weather_append.txt after weather fullscreen\n"
         "      character/room_append.txt after describe / blurb / room fullscreen\n"
         "      character/recap_append.txt after recap / transcript fullscreen\n"
         "      character/help_append.txt after help / ? fullscreen\n"
         "      character/about_append.txt after about / credits fullscreen\n"
         "      character/lights_append.txt after lights / lighting fullscreen\n"
         "      character/exits_append.txt after exits fullscreen\n"
         "      character/scan_append.txt after scan fullscreen\n"
         "      character/trail_append.txt after trail fullscreen\n"
         "\n"
         "COMMANDS & CHECKS\n"
         "-----------------\n"
         "  mods reload   —  rescan packs from disk\n"
         "  mods list     —  pack load order (manifest priority, folder name)\n"
         "  mods doctor   —  runtime bootstrap health + overlay warnings if any\n"
         "                   (unknown room/title slug, unreadable file, path too long)\n"
         "  mods doctor verbose  —  same plus full merged overlay summary\n"
         "\n"
         "[CI autotest: arrow-key pager skipped; use help modding interactively.]";
}
